# GEMINI_API_KEY = "AIzaSyAtVItFrzD555u1rv_56mfIhrPu1WnACD4"
# GEMINI_API_KEY = "AIzaSyCLH-xZjLz0sDmFlpOXVe2yUcg8sEIq2Vc"
# GEMINI_API_KEY = "AIzaSyCLH-xZjLz0sDmFlpOXVe2yUcg8sEIq2Vc"
# GEMINI_API_KEY = "AIzaSyDEWBdU1jTqNeHCzau5DZwZab01BthuSmc"
# GEMINI_API_KEY = "AIzaSyCv3CFah-vCMsIOvYL6hxs8T8u5HRexbic"
GEMINI_API_KEY = "AIzaSyAkZrBafraTz-xX31fQ7ftRkkjXqXISgto"
PATHWAY_LICENSE_KEY = "F409DD-99BCC5-CBDD3B-C742C2-470F6E-V3"
HOST = "0.0.0.0"
PORT = 8666
GEMINI_API_URL = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key={GEMINI_API_KEY}"
REQUEST_HEADERS = {
    'Content-Type': 'application/json',
}
DATA_FOLDER = "data"
CLEANED_DATA_FOLDER = "documentations"
DDGS_MAX_RESULTS_THRESHOLD = 5
THRESHOLD = 0.3
CONTEXT_KEY = "CONTEXT"
SYSTEM_INSTRUCTIONS_KEY = "SYSTEM_INSTRUCTIONS"
TOP_K = 5
CHUNK_SIZE = 512
CHUNK_OVERLAP = 20
UNSTRUCTURED_API_KEY = 'UNSTRUCTURED_API_KEY'
UNSTRUCTURED_API_URL = 'https://api.unstructuredapp.io/general/v0/general'
CSV_FOLDER = "csv_files"
TABLE_KEY = "TABLE_FILE_NAME"
TABLE_SYNTAX = f"$[[table_{TABLE_KEY}]]"
OPENAI_API_KEY = "YOUR_API_KEY"
MAX_DECOMPOSITION_DEPTH = 4