import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google'

const spaceGrotesk = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Agentic RAG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased  ${spaceGrotesk.className}`}
      >
        {children}
      </body>
    </html>
  );
}
