import dspy
from pydantic import BaseModel


class GenerateResponse(dspy.Signature):
    """Generate a response based on a query and documents as an help agent.
    Answer should be fun and very concise. No need for adding more info by yourself. The api_response is the data you have, answer from that data only.
    Never ever say that you do not have access to any sort of information. Never ever.
    """
    query = dspy.InputField(desc="User's Query")
    api_response = dspy.InputField(
        desc="Data retrieved from a database about the user's query. Please answer from this data.")
    response = dspy.OutputField(
        desc="The 'response' key in the api_response mentions the response from the API. Please answer using that data and do not mention that you are using any APIs. Act as if you had the data beforehand.")


class GenerateResponseUsingCodeOutput(dspy.Signature):
    """Generate a response based on a query and its answer.
    """
    query = dspy.InputField(desc="User's Query")
    answer = dspy.InputField(desc="Answer to the query")
    response = dspy.OutputField(
        desc="Response to be generated by the language model and if the answer is 'None' just return that the query has been completed")


class GenerateResponseWithoutCodeOutput(dspy.Signature):
    """Generate a response based on a query and its answer.
    """
    query = dspy.InputField(desc="User's Query")
    response = dspy.OutputField(
        desc="A sentence saying User's query has been completed")
